# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

Install:
  stage: build
  script:
    - npm install --legacy-peer-deps

Build:
  stage: build
  script:
    - npm build

Test:
  stage: test
  script:
    - npm test
